'use strict';
const assert=require('node:assert/strict');
const C=require('../js/decision-confidence.js');
const fs=require('node:fs'),path=require('node:path');
const fresh={level:'FRESH'};
const coverage={eligible_rate:1};
const validation={components:{wwpa:{status:'estimated',calibration_status:'pending'},auction:{status:'historically_backtested',calibration_status:'limited'}}};
const trust=C.confidence({sourceHealth:fresh,projectionCoverage:coverage,evaluation:{confidence:90},validation});
assert.equal(trust.label,'HIGH');
assert.equal(trust.calibrated,false);
assert.ok(trust.reasons.some(reason=>reason.includes('calibration')));
assert.ok(C.confidence({sourceHealth:fresh,projectionCoverage:{complete:true,eligiblePlayers:240,poolPlayers:240},evaluation:{confidence:90},validation}).score>=trust.score-1);
const modeled=C.confidence({sourceHealth:fresh,projectionCoverage:{complete:true,eligiblePlayers:240,poolPlayers:240,directPlayers:30,openModelPlayers:210},evaluation:{confidence:90},validation});
assert.ok(modeled.score<trust.score);
assert.ok(modeled.reasons.some(reason=>reason.includes('open-model')));
const snake=C.snakeCard({player:{name:'Example RB'},evaluation:{confidence:85,wwpa:{winRateAfter:58}},sourceHealth:fresh,projectionCoverage:coverage,validation,scenario:{decision:'Draft Example RB',expectedWaitLoss:7}});
assert.equal(snake.headline,'Draft Example RB');
assert.ok(snake.range.low<58&&snake.range.high>58);
const early=C.confidence({round:1,player:{agreement:96},sourceHealth:{level:'DEGRADED'},projectionCoverage:{complete:true,eligiblePlayers:240,poolPlayers:240,directPlayers:40,openModelPlayers:200},evaluation:{confidence:84},validation});
assert.ok(early.score>=70,'complete early-round evidence should not display a single-digit score');
const policySnake=C.snakeCard({round:1,player:{name:'Example RB',agreement:96},evaluation:{confidence:84,wwpa:{winRateAfter:58}},sourceHealth:{level:'DEGRADED'},projectionCoverage:coverage,validation:{...validation,components:{...validation.components,draft_policy:{historical_win_rate:.542,snake_sample_size:96}}}});
assert.match(policySnake.proof,/54\.2% of 96 snake replays/);
const auction=C.auctionCard({evaluation:{current:27,maxBid:31,draft:{confidence:80,wwpa:{winRateAfter:57}},nextComparable:{price:22}},sourceHealth:fresh,projectionCoverage:coverage,validation,minBid:1});
assert.equal(auction.bidThrough,31);
assert.equal(auction.walkAway,32);
assert.equal(auction.savings,5);
const published=JSON.parse(fs.readFileSync(path.join(__dirname,'..','data','model_validation.json'),'utf8'));
assert.equal(published.status,'research');
assert.equal(published.components.wwpa.calibration_status,'pending');
assert.equal(published.promotion_gates.time_lock_required,true);
console.log('decision confidence tests passed');
