'use strict';
const assert = require('node:assert/strict');
const E = require('../js/league-decision-engine.js');
const { fixture } = require('./fixtures/league-decisions.cjs');
const configs = ['redraft', 'dynasty', 'bestball', 'idp'].map(fixture);
assert.equal(configs[0].format.numQbs, 1); assert.equal(configs[0].format.ppr, 1); assert.equal(configs[0].format.dynasty, false);
assert.equal(configs[1].format.superFlex, 1); assert.equal(configs[1].format.tePremium, 0.5);
assert.equal(configs[2].format.bestBall, true); assert.equal(configs[3].format.idpSlots.length, 4);
assert.match(E.marketUrl(configs[0].format), /isDynasty=false&numQbs=1&numTeams=4&ppr=1/);
assert.match(E.marketUrl(configs[1].format), /isDynasty=true&numQbs=2/);
const custom = E.format({ ...configs[0].league, scoring_settings: { rec: 0.75 } }); assert.equal(custom.ppr, 0.75); assert(custom.warnings.some(w => /Custom/.test(w)));
assert(Object.isFrozen(custom)); assert(Object.isFrozen(custom.slots));
const players = { a: { full_name: 'D’Andre Swift Jr.', position: 'RB' }, b: { full_name: 'Same Name', position: 'WR' }, c: { full_name: 'Same Name', position: 'WR' }, d: { full_name: 'Same Name', position: 'RB' } };
const rows = [{ player: { name: "D'Andre Swift", position: 'RB' }, value: 500 }, { player: { name: 'Same Name', position: 'WR' }, value: 900 }, { player: { sleeperId: 'bad-id', name: "D'Andre Swift", position: 'RB' }, value: 2000 }];
const joined = E.joinValues(players, rows, 'FantasyCalc', 'now', configs[0].format);
assert.equal(joined.values.a.value, 500); assert.equal(joined.fuzzy.length, 1); assert.equal(joined.unmatched.length, 2); assert.equal(Object.keys(joined.values).length, 1);
const dp = E.csv('"player","pos","value_1qb","value_2qb"\r\n"D’Andre Swift Jr.","RB",12,34\r\n"Doe, John","WR",8,9');
assert.equal(dp[1].player, 'Doe, John'); assert.equal(E.joinValues(players, dp, 'DynastyProcess', 'now', configs[1].format).values.a.value, 34);
assert.equal(E.sum([12, null]), null); assert.equal(E.sum([0, 10]), 10);
const flexible = E.optimize([{ id: 'multi', positions: ['QB', 'RB'], value: 10 }, { id: 'rb', positions: ['RB'], value: 9 }], ['RB', 'QB']);
assert.equal(flexible.total, 19); assert.equal(flexible.rows[1].player.id, 'multi');
assert.equal(E.optimize([{ id: 'missing', positions: ['QB'], value: null }], ['QB']).total, null);
for (const ctx of configs) {
  const l = E.lineup(ctx, 1); assert(l.complete); assert.equal(l.metric, 'value');
  const ids = l.rows.map(r => r.player.id); assert.equal(new Set(ids).size, ids.length);
  l.rows.forEach(r => assert(E.eligible(r.player, r.slot)));
  const waivers = E.waivers(ctx, 1); assert.equal(waivers.remaining, 60); assert.equal(waivers.rows.find(p => p.id === 'free').bid, 12); assert(!waivers.rows.some(p => p.id === 't1p0'));
  assert.equal(waivers.rows.find(p => p.id === 'unvalued').value, null);
  const offers = E.tradeFindPartner(ctx, 1); assert(offers.length > 0, `${ctx.league.name}: offers expected`);
  offers.forEach(o => { assert(!E.fairness(o.give, o.receive).flagged); assert(o.myGain > 0); assert(o.theirGain >= 0); assert(o.give.every(p => ctx.rosters[0].players.includes(p.id))); assert(o.receive.every(p => ctx.rosters.find(r => r.roster_id === o.owner).players.includes(p.id))); assert.equal(new Set([...o.give, ...o.receive].map(p => p.id)).size, o.give.length + o.receive.length); });
  assert(offers.some(o => o.give.length >= 2));
  const simulation = E.playoffs(ctx, 1, 10, 42); assert(simulation.available, simulation.reason); assert.equal(simulation.sims, 5000);
  simulation.teams.forEach(t => assert(Math.abs(t.seeds.reduce((a, b) => a + b, 0) - 1) < 1e-9));
  assert(Math.abs(simulation.teams.reduce((a, b) => a + b.odds, 0) - ctx.format.playoffTeams) < 1e-9);
  assert.deepEqual(simulation, E.playoffs(ctx, 1, 5000, 42));
  assert(!E.playoffs({ ...ctx, matchups: { ...ctx.matchups, 7: null } }, 1).available);
  assert(!E.playoffs({ ...ctx, week: 1 }, 1).available);
}
assert(E.fairness([{ value: 100 }], [{ value: 84 }]).flagged); assert(!E.fairness([{ value: 100 }], [{ value: 85 }]).flagged);
assert(E.fairness([{ value: null }], [{ value: 85 }]).flagged);
const consolidationSizes = E.tradeFindPartner(fixture('redraft'), 1).map(o => o.give.length);
assert(consolidationSizes.includes(2)); assert(consolidationSizes.includes(3));
const ctx = fixture(); ctx.rosters[0].reserve = ['t1p0']; assert(!E.lineup(ctx, 1).rows.some(r => r.player?.id === 't1p0'));
const cap = E.capital(ctx); assert.equal(cap.teams[0].count, 4); assert.equal(cap.teams[0].value, null); assert.equal(cap.teams[0].net, null);
ctx.market.picks = [1, 2, 3].map((round, i) => ({ name: `2027 ${['1st', '2nd', '3rd'][i]}`, value: 100 / round }));
assert(Math.abs(E.capital(ctx).teams[0].net - 100) < 1e-9);
assert.equal(E.capital({ ...ctx, tradedPicks: null }), null);
const scored = E.projectionScores([{ player_id: 'a', week: 1, stats: { rec: 4, rec_yd: 50, rush_yd: 0 } }], E.format({ ...ctx.league, scoring_settings: { rec: 1, rec_yd: 0.1, rush_yd: 0.1 } }), players); assert.equal(scored.scores.a, 9);
assert.equal(Object.keys(E.projectionScores([{ player_id: 'a', week: 1, stats: { rec: 4 } }], ctx.format, players).scores).length, 0);
console.log('League decision contracts passed: four formats, joins, optimal eligibility, owner/fairness invariants, waivers, 5000-run simulation and pick integrity.');
