from pathlib import Path

p=Path('draft.html')
s=p.read_text()
repls=[
(".order-row.mine{border:1px solid rgba(245,158,11,.55)}", ".order-row.mine{border:1px solid rgba(245,158,11,.55)}.qualifiers{display:flex;gap:4px;flex-wrap:wrap;margin-top:4px}.qualifier{display:inline-grid;place-items:center;min-width:23px;height:23px;padding:0 5px;border:1px solid var(--border);border-radius:6px;background:var(--surface2);font-size:12px;font-weight:800}.qualifier.positive{color:var(--green)}.qualifier.caution{color:var(--gold)}.qualifier.risk{color:var(--red)}.qualifier.market{color:var(--teal)}.qualifier-legend{display:flex;gap:6px;flex-wrap:wrap;margin:8px 0}.qualifier-key{font-size:10px;color:var(--muted);display:inline-flex;gap:4px;align-items:center}"),
("<div id=\"source-note\" class=\"info\"></div><div id=\"board-list\" class=\"board-list\"></div>", "<div id=\"source-note\" class=\"info\"></div><div id=\"qualifier-legend\" class=\"qualifier-legend\"></div><div id=\"board-list\" class=\"board-list\"></div>"),
("const state={league:null,rosters:[],users:[],drafts:[],draft:null,picks:[],players:{},values:[],fp:{},watch:{},prospects:{players:[]},myRosterId:null", "const state={league:null,rosters:[],users:[],drafts:[],draft:null,picks:[],players:{},values:[],fp:{},watch:{},prospects:{players:[]},qualifierConfig:{qualifiers:{}},myRosterId:null"),
("function recommendations(){return playerPool().slice(0,60).map((x,i)=>({...x,rank:i+1,...scorePlayer(x,i)})).sort((a,b)=>b.score-a.score||b.value-a.value)}", "function qualifierKeys(r){const keys=[];const valueNorm=Math.min(100,Math.round(r.value/85));if(r.rank<=4&&r.score>=78&&r.confidence>=75)keys.push('blue_chip');else if(r.score>=70&&r.confidence>=60)keys.push('prototype');if(r.trend>40&&r.rank>10&&r.score-valueNorm>=8)keys.push('hidden_gem');if(r.trend>20&&r.confidence>=50)keys.push('breakout');if(r.trend>0)keys.push('opportunity_rising');if(r.score-valueNorm>=10)keys.push('market_lag');if(r.trend>30&&r.confidence<50)keys.push('false_breakout');if(r.confidence>=75)keys.push('verified');else keys.push('small_sample');if(r.trend<-25)keys.push('decline');return [...new Set(keys)].slice(0,4)}\nfunction qualifierHTML(r){return qualifierKeys(r).map(k=>{const q=state.qualifierConfig.qualifiers?.[k]||{icon:'?',label:k,meaning:k,category:'confidence'};const cls=['risk','confidence'].includes(q.category)?(k==='verified'?'positive':'risk'):q.category==='market'?'market':q.category==='action'||q.category==='development'?'positive':'caution';return `<span class=\"qualifier ${cls}\" title=\"${esc(q.label)} — ${esc(q.meaning)}\" aria-label=\"${esc(q.label)}\">${esc(q.icon)}</span>`}).join('')}\nfunction renderQualifierLegend(){const keys=['blue_chip','prototype','hidden_gem','breakout','market_lag','false_breakout','small_sample','verified'];$('qualifier-legend').innerHTML=keys.map(k=>{const q=state.qualifierConfig.qualifiers?.[k];return q?`<span class=\"qualifier-key\"><span class=\"qualifier\" title=\"${esc(q.meaning)}\">${esc(q.icon)}</span>${esc(q.label)}</span>`:''}).join('')}\nfunction recommendations(){return playerPool().slice(0,60).map((x,i)=>({...x,rank:i+1,...scorePlayer(x,i)})).sort((a,b)=>b.score-a.score||b.value-a.value)}"),
("const [league,rosters,users,drafts,players,values,fp,watch,prospects]=await Promise.all([json(`${API}/league/${id}`),json(`${API}/league/${id}/rosters`),json(`${API}/league/${id}/users`),json(`${API}/league/${id}/drafts`),json(`${API}/players/nfl`),json(FC),optionalJson('fantasypros.json'),optionalJson('watcher_state.json'),optionalJson('data/prospect_board.json')]);state.league=league;state.rosters=rosters;state.users=users;state.drafts=drafts;state.players=players;state.values=values;state.fp=fp||{};state.watch=watch||{};state.prospects=prospects||{players:[]};", "const [league,rosters,users,drafts,players,values,fp,watch,prospects,qualifiers]=await Promise.all([json(`${API}/league/${id}`),json(`${API}/league/${id}/rosters`),json(`${API}/league/${id}/users`),json(`${API}/league/${id}/drafts`),json(`${API}/players/nfl`),json(FC),optionalJson('fantasypros.json'),optionalJson('watcher_state.json'),optionalJson('data/prospect_board.json'),optionalJson('config/player_qualifiers.json')]);state.league=league;state.rosters=rosters;state.users=users;state.drafts=drafts;state.players=players;state.values=values;state.fp=fp||{};state.watch=watch||{};state.prospects=prospects||{players:[]};state.qualifierConfig=qualifiers||{qualifiers:{}};"),
("${decl?`<div class=\"meta\">Declaration: ${esc(decl)}</div>`:''}</div></div>", "${decl?`<div class=\"meta\">Declaration: ${esc(decl)}</div>`:''}<div class=\"qualifiers\">${qualifierHTML(r)}</div></div></div>"),
("function renderBoard(){renderFilters();const recs=recommendations();", "function renderBoard(){renderFilters();renderQualifierLegend();const recs=recommendations();"),
("$('rec-confidence').textContent=`${r.confidence}%`;const warn=[];", "$('rec-confidence').textContent=`${r.confidence}%`;$('rec-reason').innerHTML=`League-adjusted recommendation using market value, roster need, format, projections, trend and declaration certainty. Score gap: ${gap}.<div class=\"qualifiers\" style=\"margin-top:8px\">${qualifierHTML(r)}</div>`;const warn=[];")
]
for old,new in repls:
    if old not in s:
        raise SystemExit(f'Missing expected marker: {old[:80]}')
    s=s.replace(old,new,1)
p.write_text(s)
print('Qualifier UI applied')
